class OrderResponse {
  List<Orders> _orders;

  Autogenerated({List<Orders> orders}) {
    this._orders = orders;
  }

  List<Orders> get orders => _orders;

  set orders(List<Orders> orders) => _orders = orders;

  OrderResponse.fromJson(Map<String, dynamic> json) {
    if (json['orders'] != null) {
      _orders = new List<Orders>();
      json['orders'].forEach((v) {
        _orders.add(new Orders.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._orders != null) {
      data['orders'] = this._orders.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Orders {
  int _orderId;
  String _orderDate;
  String _orderPrice;
  String _productDetails;
  String _orderStatus;
  String _orderDeliveryDate;

  Orders(
      {int orderId,
      String orderDate,
      String orderPrice,
      String productDetails,
      String orderStatus,
      String orderDeliveryDate}) {
    this._orderId = orderId;
    this._orderDate = orderDate;
    this._orderPrice = orderPrice;
    this._productDetails = productDetails;
    this._orderStatus = orderStatus;
    this._orderDeliveryDate = orderDeliveryDate;
  }

  int get orderId => _orderId;

  set orderId(int orderId) => _orderId = orderId;

  String get orderDate => _orderDate;

  set orderDate(String orderDate) => _orderDate = orderDate;

  String get orderPrice => _orderPrice;

  set orderPrice(String orderPrice) => _orderPrice = orderPrice;

  String get productDetails => _productDetails;

  set productDetails(String productDetails) => _productDetails = productDetails;

  String get orderStatus => _orderStatus;

  set orderStatus(String orderStatus) => _orderStatus = orderStatus;

  String get orderDeliveryDate => _orderDeliveryDate;

  set orderDeliveryDate(String orderDeliveryDate) =>
      _orderDeliveryDate = orderDeliveryDate;

  Orders.fromJson(Map<String, dynamic> json) {
    _orderId = json['orderId'];
    _orderDate = json['orderDate'];
    _orderPrice = json['orderPrice'];
    _productDetails = json['productDetails'];
    _orderStatus = json['orderStatus'];
    _orderDeliveryDate = json['orderDeliveryDate'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['orderId'] = this._orderId;
    data['orderDate'] = this._orderDate;
    data['orderPrice'] = this._orderPrice;
    data['productDetails'] = this._productDetails;
    data['orderStatus'] = this._orderStatus;
    data['orderDeliveryDate'] = this._orderDeliveryDate;
    return data;
  }
}
